#!/bin/bash
#first
#THis file looks throught all the files in  the current
#directory for the strign POSIX, and then prints the names of 
#those files to the standard output.

for file in *
do
    if grep -q POSIX $file
    then
        echo $file
    fi
done

exit 0
